run:
  timeout: 3m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - varnamelen
    - goimports
    - cyclop # duplicate of gocyclo
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - dupl
    - testpackage
    - tparallel
    - paralleltest
    - nlreturn
    - wsl
    - exhaustive
    - err113
    - wrapcheck
    - noctx
    - lll
    - forbidigo
    - exportloopref # deprecated
    - depguard
    - exhaustruct
    - mnd
    - gochecknoglobals

issues:
  exclude-use-default: true
  max-same-issues: 0
  exclude-dirs:
    - pkg/
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
        - revive
